// unit_Interface.h //                     Author: Logan "Burn" Jones
/////////////////////                                 Date: 10/6/2002
//
/////////////////////////////////////////////////////////////////////
#ifndef _UNIT_INTERFACE_H_
#define _UNIT_INTERFACE_H_
/////////////////////////////////////////////////////////////////////


////////////////////////// unit_Interface //////////////////////////
//
class unit_Interface
{
	friend class game_Main;

/////////////////////////////////////////////////
// Client side events
public:

	// Unit was selected in the igui. Show a selection rect and play
	// a sound or something
	virtual void OnSelect( bool bSelected, bool bSingle ) = 0;


/////////////////////////////////////////////////
//{{AFX Net Messages (Generated by AsmNetMsg.exe. DO NOT EDIT)
public: // Requests made to the server
	void RequestStop();
	void RequestMoveTo( const std_Point& ptWhere, bool bEnqueue );
	void RequestBuild( const unit_Type* pType, const std_Point& ptWhere, bool bEnqueue );
	void RequestActivate( bool bActivate );
	void RequestAttack( const std_Point& ptWhere, bool bEnqueue );
	void RequestUnit( const unit_Type* pType );
protected: // Notifications sent to the client
	void NotifyPrepareToBuild( const unit_Type* pType, const std_Point& ptWhere );
	void NotifySpawnNewUnit( const unit_Type* pType, const std_Point& ptWhere );
protected: // Virtual handlers called by the translator and implemented in a derived class
	virtual void OnRequestStop() = 0;
	virtual void OnRequestMoveTo( const std_Point& ptWhere, bool bEnqueue ) = 0;
	virtual void OnRequestBuild( const unit_Type* pType, const std_Point& ptWhere, bool bEnqueue ) = 0;
	virtual void OnRequestActivate( bool bActivate ) = 0;
	virtual void OnRequestAttack( const std_Point& ptWhere, bool bEnqueue ) = 0;
	virtual void OnRequestUnit( const unit_Type* pType ) = 0;
	virtual void OnNotifyPrepareToBuild( const unit_Type* pType, const std_Point& ptWhere ) = 0;
	virtual void OnNotifySpawnNewUnit( const unit_Type* pType, const std_Point& ptWhere ) = 0;
//}}AFX Net Messages

/////////////////////////////////////////////////
// Data member
protected:

	// Unique value for this object
	UINT32			m_UniqueID;

}; // End class - unit_Interface
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
#endif // !defined(_UNIT_INTERFACE_H_)
