//
//  app_nTA_macOS.m
//  nTA
//
//  Created by Logan Jones on 5/5/16.
//  Copyright © 2016 Logan Jones. All rights reserved.
//

#import <Foundation/Foundation.h>


/**
 Build a Windows compatible argv by distilling NSProcessInfo's arguments
 into an array of C Strings.
 
 @note Must call _FreeARGV_macOS to properly dispose of the generated argv array.
 
 @return The number of command-line arguments (argc).
 */
const int _MakeARGV_macOS(char ***pargv) {
    
    if (!pargv) { return 0; }
    
    NSArray *arguments = [[NSProcessInfo processInfo] arguments];
    const int argc = (int)arguments.count;
    
    if (argc <= 0) { return 0; }
    
    char **argv = malloc(sizeof(char **) * arguments.count);
    
    int i = 0;
    for (NSString *arg in arguments) {
        argv[i] = malloc([arg lengthOfBytesUsingEncoding:NSUTF8StringEncoding] + 1);
        strcpy(argv[i], arg.UTF8String);
        ++i;
    }
    
    *pargv = argv;
    return argc;
}

/**
 Dispose of an argv array that was generated by _MakeARGV_macOS.
 */
void _FreeARGV_macOS(char **argv, const int argc) {
    
    if (!argv) { return ; }
    
    for (int i=0; i < argc; ++i) {
        free(argv[i]);
    }
    
    free(argv);
}
