// script_Instructions.h //                        \author Logan Jones
//////////////////////////                             \date 9/1/2002
/// \file
/// \brief ...
/////////////////////////////////////////////////////////////////////


INSTRUCTION_MACRO( MovePieceWithSpeed )
INSTRUCTION_MACRO( TurnPieceWithSpeed )
INSTRUCTION_MACRO( StartSpin )
INSTRUCTION_MACRO( StopSpin )
INSTRUCTION_MACRO( ShowPiece )
INSTRUCTION_MACRO( HidePiece )
INSTRUCTION_MACRO( CachePiece )
INSTRUCTION_MACRO( DontCachePiece )
INSTRUCTION_MACRO( DontShadow )
INSTRUCTION_MACRO( MovePieceNow )
INSTRUCTION_MACRO( TurnPieceNow )
INSTRUCTION_MACRO( DontShade )
INSTRUCTION_MACRO( EmitSfx )
INSTRUCTION_MACRO( WaitForTurn )
INSTRUCTION_MACRO( WaitForMove )
INSTRUCTION_MACRO( Sleep )
INSTRUCTION_MACRO( PushConstantOntoStack )
INSTRUCTION_MACRO( PushLocalVariableOntoStack )
INSTRUCTION_MACRO( PushStaticVariableOntoStack )
INSTRUCTION_MACRO( StackAllocate )
INSTRUCTION_MACRO( SetLocalVariable )
INSTRUCTION_MACRO( SetStaticVariable )
INSTRUCTION_MACRO( PopStack )
INSTRUCTION_MACRO( Add )
INSTRUCTION_MACRO( Subtract )
INSTRUCTION_MACRO( Multiply )
INSTRUCTION_MACRO( Divide )
INSTRUCTION_MACRO( BitwiseAnd )
INSTRUCTION_MACRO( BitwiseOr )
INSTRUCTION_MACRO( Unknown1 )
INSTRUCTION_MACRO( Unknown2 )
INSTRUCTION_MACRO( Unknown3 )
INSTRUCTION_MACRO( Random )
INSTRUCTION_MACRO( GetUnitValue )
INSTRUCTION_MACRO( GetFunctionResult )
INSTRUCTION_MACRO( LessThan )
INSTRUCTION_MACRO( LessThanOrEqual )
INSTRUCTION_MACRO( GreaterThan )
INSTRUCTION_MACRO( GreaterThanOrEqual )
INSTRUCTION_MACRO( Equal )
INSTRUCTION_MACRO( NotEqual )
INSTRUCTION_MACRO( And )
INSTRUCTION_MACRO( Or )
INSTRUCTION_MACRO( Not )
INSTRUCTION_MACRO( StartScript )
INSTRUCTION_MACRO( CallScript )
INSTRUCTION_MACRO( JumpToOffset )
INSTRUCTION_MACRO( Return )
INSTRUCTION_MACRO( JumpToOffsetIfFalse )
INSTRUCTION_MACRO( Signal )
INSTRUCTION_MACRO( SetSignalMask )
INSTRUCTION_MACRO( Explode )
INSTRUCTION_MACRO( PlaySound )
INSTRUCTION_MACRO( MapCommand )
INSTRUCTION_MACRO( SetUnitValue )
INSTRUCTION_MACRO( AttachUnit )
INSTRUCTION_MACRO( DropUnit )


/////////////////////////////////////////////////////////////////////
