// unit_Group.h //                                 \author Logan Jones
/////////////////                                      \date 5/2/2002
/// \file
/// \brief ...
/////////////////////////////////////////////////////////////////////
#ifndef _UNIT_GROUP_H_
#define _UNIT_GROUP_H_
/////////////////////////////////////////////////////////////////////


///////////////////////////// unit_Group /////////////////////////////
//
class unit_Group : public unit_Interface
{

/////////////////////////////////////////////////
// INTERFACE
public:

	void Add( class unit_Object* pUnit );
	void Remove( class unit_Object* pUnit );

	void Reset();
	void Filter();


/////////////////////////////////////////////////
//{{AFX Net Messages (Generated by AsmNetMsg.exe. DO NOT EDIT)
protected: // Net Message Handlers
	void OnRequestStop();
	void OnRequestMoveTo( const std_Point& ptWhere, bool bEnqueue );
	void OnRequestBuild( const unit_Type* pType, const std_Point& ptWhere, bool bEnqueue );
	void OnRequestActivate( bool bActivate );
	void OnRequestAttack( const std_Point& ptWhere, bool bEnqueue );
	void OnRequestUnit( const unit_Type* pType );
	void OnNotifyPrepareToBuild( const unit_Type* pType, const std_Point& ptWhere );
	void OnNotifySpawnNewUnit( const unit_Type* pType, const std_Point& ptWhere );
//}}AFX Net Messages


/////////////////////////////////////////////////
// Default Constructor/Deconstructor
public:
	unit_Group();
	virtual ~unit_Group();
/////////////////////////////////////////////////

}; // End class - unit_Group
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
#endif // !defined(_UNIT_GROUP_H_)
